config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tasks do
    resources :notes, only: [:create], controller: 'tasks/notes'
  end
  
  resources :categories

  # Para dejar Tasks#index como la página principal
  root 'tasks#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id          :bigint           not null, primary key
#  name        :string
#  description :text
#  due_date    :date
#  category_id :bigint           not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  owner_id    :bigint           not null
#  code        :string
#
class Task < ApplicationRecord
  belongs_to :category
  belongs_to :owner, class_name: 'User'
  has_many :participating_users, class_name: 'Participant'
  has_many :participants, through: :participating_users, source: :user
  # Puede tener muchas notas
  has_many :notes

  validates :participating_users, presence: true

  validates :name, :description, presence: true
  validates :name, uniqueness: { case_insensitive: false }
  validate :due_date_validity
  
  # Un callback que me ayuda a ejecutar codigo antes de que se guarde un archivo
  before_create :create_code

  # Para mandar el mail
  after_create :send_email
  
  accepts_nested_attributes_for :participating_users, allow_destroy: true
  
  def due_date_validity
  
    return if due_date.blank?
    return if due_date > Date.today

    errors.add :due_date, I18n.t('tasks.errors.invalid_due_date')

  end

  def create_code
    
    # Podemos verlo como un código de unicidad de la tarea
    # SecureRandom es una clase que nos da Rails para poder generar buenos aleatorios
    # Y con el .to_s(36) Lo convertimos en un string de base 36 para asegurarnos que no sea un numero muy grande
    self.code = "#{owner_id}#{Time.now.to_i.to_s(36)}#{SecureRandom.hex(8)}"

  end

  def send_email
    
    (participants + [owner]).each do |user|

      ParticipantMailer.with(user: user, task: self).new_task_email.deliver!
    
    end

  end

end

app/controllers/tasks/notes_controller.rb
class Tasks::NotesController < ApplicationController
  before_action :set_task

  def create
    
    @note = @task.notes.new(note_params)
    @note.user = current_user
    @note.save

  end

  private

  # Debido a que los paramans están altamente protegidos,
  # debemos hacer lo siguiente:
  def note_params
    
    params.require(:note).permit(:body)

  end

  def set_task
    @task = Task.find(params[:task_id])
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  #Para que ability-cancancan funcione añadimos la línea:
  load_and_authorize_resource

  before_action :set_task, only: %i[ show edit update destroy ]

  # GET /tasks or /tasks.json
  def index
    # Filtro para que solo me muestren las tareas
    # a las que estoy asignado y las tareas que yo cree
    @tasks = Task.joins(:participants).where(
      'owner_id = ? OR participants.user_id = ?',
      current_user.id,
      current_user.id,
    ).group(:id)
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    @task = Task.new(task_params)
    @task.owner = current_user
    respond_to do |format|
      if @task.save
        format.html { redirect_to task_url(@task), notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to task_url(@task), notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:name, 
        :description, 
        :due_date, 
        :category_id,
        participating_users_attributes: [
          :user_id,
          :role,
          :id,
          :_destroy # Le indico qe podré eliminar un participante
        ]
      )
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@task) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :name, label: t('common.name')
    = f.input :description, label: t('common.description')
    = f.input :due_date, label: t('common.due_date')
    = f.association :category, label: t('common.category')
    #addParticipants
      = link_to_add_association f,  :participating_users, 'data-association-insertion-node' => '.participants .participants-container', 'data-turbolinks' => false do
        agregar participante
    .participants 
      = f.simple_fields_for :participating_users do |g|
        = render 'participating_user_fields', f: g
      .participants-container

  .form-actions
    = f.button :submit

app/views/tasks/_participating_user_fields.html.haml
.nested-fields
    = f.input :user_id, as: :select, collection: User.all - [current_user]
    = f.input :role

app/views/tasks/edit.html.haml
%h1= t('.Editing_task')

= render 'form'

= link_to t('common.show'), @task
\|
= link_to t('common.back'), tasks_path

app/views/tasks/index.html.haml
%h1= t('.Listing_tasks')

%table
  %thead
    %tr
      %th= t('common.name')
      %th= t('common.description')
      %th= t('common.due_date')
      %th= t('common.category')
      %th
      %th
      %th

  %tbody
    - @tasks.each do |task|
      %tr
        %td= task.name
        %td= task.description
        %td= task.due_date
        %td= task.category
        %td= link_to t('common.show'), task
        %td= link_to t('common.edit'), edit_task_path(task)
        %td= link_to t('common.destroy'), task, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to t('common.New_Task'), new_task_path

app/views/tasks/new.html.haml
%h1 New task

= render 'form'

= link_to t('common.back'), tasks_path

app/views/tasks/show.html.haml
%p#notice= notice

%p
  %b= t('common.name') + ":"
  = @task.name
%p
  %b= t('common.description') + ":"
  = @task.description
%p
  %b= t('common.due_date') + ":"
  = @task.due_date
%p
  %b= t('common.category') + ":"
  = @task.category

.notes-container
  .notes
    - @task.notes.each do |note|
      = render 'tasks/notes/note.html.haml', note: note 

  = simple_form_for Note.new, url: task_notes_path(task_id: @task.id), remote: true do |f|
    = f.input :body, label: false, as: :string, placeholder: 'Digite su nota', input_html: { autocomplete: :off }

= link_to t('common.edit'), edit_task_path(@task)
\|
= link_to t('common.back'), tasks_path